package dev.superchunk.com.ishland.c2me.opts.dfc.common.ast.noise;

import dev.superchunk.com.ishland.c2me.opts.dfc.common.ast.AstNode;
import dev.superchunk.com.ishland.c2me.opts.dfc.common.ast.misc.DelegateNode;
import net.minecraft.world.level.levelgen.synth.BlendedNoise;

/**
 * SuperChunk GPU: a typed AST leaf for vanilla {@link BlendedNoise}
 * ({@code old_blended_noise}) — previously this fell into {@code McToAst}'s
 * {@code default} case as an opaque {@link DelegateNode}, which made every DF
 * containing it (notably the router {@code finalDensity} and its MAIN-terrain
 * interpolated grid) refuse to GPU-compile.
 *
 * <p><b>CPU semantics are inherited from {@link DelegateNode} unchanged</b>:
 * {@code evalSingle}/{@code evalMulti}/bytecode-gen all call
 * {@code blendedNoise.compute(...)} on the captured vanilla instance, exactly
 * as the old opaque node did — bit-identical CPU behavior by construction
 * (nothing is baked into the generated bytecode; the instance is field-injected).
 * The ONLY new capability is GPU emission: {@code OpenCLAstEmitter} recognizes
 * this subtype (BEFORE its {@code DelegateNode} branch) and emits a
 * {@code df_blended_noise(...)} call with this node's captured parameters and
 * the octave tables registered via {@code NoiseRegistry#registerBlended}.
 *
 * <p>The scale parameters are captured eagerly from the (access-widened) vanilla
 * fields: {@code xzMultiplier}/{@code yMultiplier} are the CONSTRUCTED products
 * {@code 684.412 * xzScale} / {@code 684.412 * yScale} (field values, never
 * recomputed — exact bits); {@code xzFactor}/{@code yFactor}/{@code
 * smearScaleMultiplier} are the raw codec doubles. The three legacy
 * {@code PerlinNoise} samplers stay reachable through {@link #getBlendedNoise()}.
 *
 * <p>{@code equals}/{@code hashCode} are inherited (class + delegate identity).
 * {@code relaxedEquals}/{@code relaxedHashCode} are overridden to also compare
 * the five scalar parameters — mirroring {@code DFTNoiseNode} (tables excluded,
 * scalars included). This is strictly finer than the inherited class-only
 * relaxed equality, and remains correct for the C2ME bytecode compilation cache
 * because the generated CPU class bakes nothing (instance field-injected).
 */
public class BlendedNoiseNode extends DelegateNode {

    private final BlendedNoise blendedNoise;
    private final double xzMultiplier;
    private final double yMultiplier;
    private final double xzFactor;
    private final double yFactor;
    private final double smearScaleMultiplier;

    public BlendedNoiseNode(BlendedNoise blendedNoise) {
        super(blendedNoise);
        this.blendedNoise = blendedNoise;
        // AT-widened reads (accesstransformer.cfg): the exact constructed field bits.
        this.xzMultiplier = blendedNoise.xzMultiplier;
        this.yMultiplier = blendedNoise.yMultiplier;
        this.xzFactor = blendedNoise.xzFactor;
        this.yFactor = blendedNoise.yFactor;
        this.smearScaleMultiplier = blendedNoise.smearScaleMultiplier;
    }

    public BlendedNoise getBlendedNoise() {
        return this.blendedNoise;
    }

    /** The constructed {@code 684.412 * xzScale} field value (exact bits). */
    public double getXzMultiplier() {
        return this.xzMultiplier;
    }

    /** The constructed {@code 684.412 * yScale} field value (exact bits). */
    public double getYMultiplier() {
        return this.yMultiplier;
    }

    public double getXzFactor() {
        return this.xzFactor;
    }

    public double getYFactor() {
        return this.yFactor;
    }

    public double getSmearScaleMultiplier() {
        return this.smearScaleMultiplier;
    }

    @Override
    public boolean relaxedEquals(AstNode o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BlendedNoiseNode that = (BlendedNoiseNode) o;
        return Double.compare(xzMultiplier, that.xzMultiplier) == 0
                && Double.compare(yMultiplier, that.yMultiplier) == 0
                && Double.compare(xzFactor, that.xzFactor) == 0
                && Double.compare(yFactor, that.yFactor) == 0
                && Double.compare(smearScaleMultiplier, that.smearScaleMultiplier) == 0;
    }

    @Override
    public int relaxedHashCode() {
        int result = 1;
        result = 31 * result + this.getClass().hashCode();
        result = 31 * result + Double.hashCode(xzMultiplier);
        result = 31 * result + Double.hashCode(yMultiplier);
        result = 31 * result + Double.hashCode(xzFactor);
        result = 31 * result + Double.hashCode(yFactor);
        result = 31 * result + Double.hashCode(smearScaleMultiplier);
        return result;
    }
}
