package dev.superchunk.com.ishland.c2me.opts.dfc.common.ast;

import dev.superchunk.com.ishland.c2me.base.mixin.access.IDensityFunctionTypesWeirdScaledSamplerRarityValueMapper;
import net.minecraft.util.Mth;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.DensityFunctions;

/**
 * All called from generated code.
 *
 * <p>This replaces the Fabric {@code MappingResolver}-based intermediary remapping that the
 * upstream module used inside its ASM codegen. On NeoForge the generated bytecode targets
 * these static shim methods, which themselves call the (already Mojmap-named) Minecraft
 * methods directly, so no runtime name remapping is required.</p>
 */
public class InvocationShim {

    public static double invokeDensityFunctionSample(DensityFunction densityFunction, DensityFunction.FunctionContext pos) {
        return densityFunction.compute(pos);
    }

    public static void invokeDensityFunctionFill(DensityFunction densityFunction, double[] densities, DensityFunction.ContextProvider applier) {
        densityFunction.fillArray(densities, applier);
    }

    public static double invokeMathHelperClampedMap(double value, double oldStart, double oldEnd, double newStart, double newEnd) {
        return Mth.clampedMap(value, oldStart, oldEnd, newStart, newEnd);
    }

    public static double invokeDensityFunctionNoiseSample(DensityFunction.NoiseHolder noise, double x, double y, double z) {
        return noise.getValue(x, y, z);
    }

    public static float invokeMathHelperLerp(float delta, float start, float end) {
        return Mth.lerp(delta, start, end);
    }

    /**
     * Yarn {@code DensityFunctions.CaveScaler#scaleCaves/scaleTunnels} have no Mojmap 1.21.1
     * equivalent. The vanilla {@code WeirdScaledSampler} instead stores the scaling function on
     * the {@code RarityValueMapper} enum constant (TYPE1/TYPE2). The interpreted path reads it via
     * the {@code mapper} accessor; the generated bytecode calls this shim so the two paths share
     * the exact same scaling logic.
     */
    public static double invokeRarityValueMapper(double value, DensityFunctions.WeirdScaledSampler.RarityValueMapper mapper) {
        return ((IDensityFunctionTypesWeirdScaledSamplerRarityValueMapper) (Object) mapper).getScaleFunction().get(value);
    }

}
