package dev.superchunk.com.ishland.c2me.fixes.worldgen.threading_issues.mixin.threading;

import dev.superchunk.com.ishland.c2me.fixes.worldgen.threading_issues.common.IStrongholdGenerator;
import dev.superchunk.com.ishland.c2me.fixes.worldgen.threading_issues.common.XPieceDataExtension;
import net.minecraft.world.level.levelgen.structure.structures.StrongholdPieces;
import org.objectweb.asm.Opcodes;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

import java.util.ArrayList;
import java.util.List;

/**
 * Mojmap port of upstream C2ME's MixinStrongholdGenerator (dropped in the original merge):
 * vanilla stronghold piece selection keeps its bookkeeping in STATIC MUTABLE fields
 * ({@code currentPieces}/{@code totalWeight}/{@code imposedPiece} — yarn
 * {@code possiblePieces}/{@code totalWeight}/{@code activePieceType}), so two strongholds
 * starting concurrently on c2me workers silently corrupt each other's piece weights
 * (truncated/malformed strongholds persisted to disk). All accesses are redirected to
 * ThreadLocals — each stronghold start is generated by a single thread, so per-thread
 * state is exactly per-start state. Method mapping (yarn -> mojmap): {@code init} ->
 * {@code resetPieces}, {@code checkRemainingPieces} -> {@code updatePieceWeight},
 * {@code pickPiece} -> {@code generatePieceFromSmallDoor}.
 */
@Mixin(StrongholdPieces.class)
public class MixinStrongholdGenerator implements IStrongholdGenerator {

    @Unique
    private static final ThreadLocal<List<StrongholdPieces.PieceWeight>> currentPiecesThreadLocal = ThreadLocal.withInitial(ArrayList::new);
    @Unique
    private static final ThreadLocal<Integer> totalWeightThreadLocal = ThreadLocal.withInitial(() -> 0);
    @Unique
    private static final ThreadLocal<Class<? extends StrongholdPieces.StrongholdPiece>> imposedPieceThreadLocal = new ThreadLocal<>();

    @Redirect(method = "resetPieces", at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces;currentPieces:Ljava/util/List;", opcode = Opcodes.PUTSTATIC), require = 1)
    private static void redirectSetCurrentPieces(List<StrongholdPieces.PieceWeight> value) {
        currentPiecesThreadLocal.set(value);
    }

    @Redirect(method = {"resetPieces", "updatePieceWeight", "generatePieceFromSmallDoor"}, at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces;currentPieces:Ljava/util/List;", opcode = Opcodes.GETSTATIC), require = 4)
    private static List<StrongholdPieces.PieceWeight> redirectGetCurrentPieces() {
        return currentPiecesThreadLocal.get();
    }

    @Redirect(method = {"updatePieceWeight", "generatePieceFromSmallDoor"}, at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces$PieceWeight;placeCount:I", opcode = Opcodes.GETFIELD), require = 2)
    private static int redirectGetPlaceCount(StrongholdPieces.PieceWeight instance) {
        return ((XPieceDataExtension) instance).c2me$getGeneratedCountThreadLocal().get();
    }

    @Redirect(method = {"resetPieces", "generatePieceFromSmallDoor"}, at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces$PieceWeight;placeCount:I", opcode = Opcodes.PUTFIELD), require = 2)
    private static void redirectSetPlaceCount(StrongholdPieces.PieceWeight pieceWeight, int value) {
        if (value == 0) {
            ((XPieceDataExtension) pieceWeight).c2me$getGeneratedCountThreadLocal().remove();
        } else {
            ((XPieceDataExtension) pieceWeight).c2me$getGeneratedCountThreadLocal().set(value);
        }
    }

    @Redirect(method = "updatePieceWeight", at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces;totalWeight:I", opcode = Opcodes.PUTSTATIC), require = 2)
    private static void redirectSetTotalWeight(int value) {
        totalWeightThreadLocal.set(value);
    }

    @Redirect(method = {"updatePieceWeight", "generatePieceFromSmallDoor"}, at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces;totalWeight:I", opcode = Opcodes.GETSTATIC), require = 2)
    private static int redirectGetTotalWeight() {
        return totalWeightThreadLocal.get();
    }

    // NOTE: upstream only redirected the pickPiece PUTSTATIC; mojmap resetPieces also writes
    // imposedPiece = null, and redirecting that too clears any stale per-thread value at each
    // stronghold-start attempt (strictly safer than leaving it on the dead static).
    @Redirect(method = {"resetPieces", "generatePieceFromSmallDoor"}, at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces;imposedPiece:Ljava/lang/Class;", opcode = Opcodes.PUTSTATIC), require = 2)
    private static void redirectSetImposedPiece(Class<? extends StrongholdPieces.StrongholdPiece> value) {
        imposedPieceThreadLocal.set(value);
    }

    @Redirect(method = "generatePieceFromSmallDoor", at = @At(value = "FIELD", target = "Lnet/minecraft/world/level/levelgen/structure/structures/StrongholdPieces;imposedPiece:Ljava/lang/Class;", opcode = Opcodes.GETSTATIC), require = 2)
    private static Class<? extends StrongholdPieces.StrongholdPiece> redirectGetImposedPiece() {
        return imposedPieceThreadLocal.get();
    }

    @Override
    public ThreadLocal<Class<? extends StrongholdPieces.StrongholdPiece>> getActivePieceTypeThreadLocal() {
        return imposedPieceThreadLocal;
    }
}
